config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#index'

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]

  resources :lists, only: %i[index show create destroy] do
    resources :items, only: %i[create update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :description,
    presence: true

  # after_validation do |item|
  #   item.destroy if item.description.blank?
  # end

  STATUS = {
    incomplete: 0,
    complete: 1
  }

  def complete?
    self.status == STATUS[:complete]
  end

  def incomplete?
    self.status == STATUS[:incomplete]
  end
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name,
            presence: true

  def name=(value)
    value = value.downcase
    super(value)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i.freeze

  validates :email,
    presence: { message: "cannot be blank." },
    format: { with: EMAIL_REGEX, message: "must be in the correct format."},
    uniqueness: { case_sensitive: false, message: "already exists, please use a different email" }

  validates :password,
    length: { minimum: 4, message: "must be four characters or longer." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def authentication_required
    if !logged_in?
      redirect_to login_path
    end
  end

  def logged_in?
    current_user != nil
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @item = @list.items.build(item_params)

    if @item.save
      flash[:notice] = 'success|The item was successfully saved to the database.'
      redirect_to list_path(@list)
    else
      flash[:notice] = 'danger|The item encountered an error.'
      redirect_to list_path(@list)
    end
  end

  def update
    @item = Item.find(params[:id])

    redirect_to list_path(@item.list) if @item.update_attributes(item_params)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to list_path(@item.list)
  end

  private

  def item_params
    params.require(:item).permit(:description, :status)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :authentication_required

  def index
    @list = List.new
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    # @item = @list.items.build
    @item = Item.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      flash[:notice] = 'success|The list was successfully saved to the database.'
      redirect_to list_path(@list)
    else
      @lists = List.all
      render :index
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  end

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:notice] = "danger|Login failed."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "success|You are now logged out."
    redirect_to login_path
  end
end

app/controllers/site_controller.rb
# frozen_string_literal: true

class SiteController < ApplicationController
  def index
    @welcome = 'Greetings...'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "success|User has been successfully registered."
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render partial: 'application/error_messages', locals: { object: object }
  end
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
  def li_class_for_item(item)
    'completed' if item.complete?
  end

  def li_for_item(item)
    tag.li class: ['list-group-item py-3', li_class_for_item(item)] do
      yield
    end
  end

  def form_for_item_status(item)
    form_for [item.list, item], html: { class: 'check-form' } do |f|
      f.check_box :status, class: 'toggle', checked: item.complete?
    end
  end
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
  def make_title_case(name)
    stop_words = %w[a an and the or for of nor]
    name.split(' ').each_with_index.map { |word, index| stop_words.include?(word) && index > 0 ? word : word.capitalize }.join(' ')
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div class="container">
    <div class="row mb-3">
      <div class="col">
        <div id="error-explanation">
          <h4>
            <%= pluralize(object.errors.size, "error") %> prevented this record from being saved.
          </h4>
          <p>The following fields have problems:</p>
          <ul>
            <% object.errors.full_messages.each do |msg| %>
              <li class="text-danger">
                <%= msg %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/items/_item_list_item.html.erb
<%= li_for_item(item) do %>
  <%= form_for_item_status(item) %>
  <span class="pl-3">
    <%= item.description %>
  </span>
  <span class="float-right">
    <%= button_to list_item_path(item.list, item), method: :delete, class: "close" do %>
      <span aria-hidden="true">&times;</span>
    <% end %>
  </span>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/_access.html.erb
<div class="col-6">
  <% if logged_in? %>
    <%= link_to "Logout", logout_path, class: "float-right mr-3" %>
  <% else %>
    <%= link_to "Login", login_path, class: "float-right mr-3"  %>
  <% end %>
</div>

app/views/layouts/_logout.html.erb
<div class="col-6">
  <% if logged_in? %>
    <%= link_to "Logout", logout_path, class: "float-right mr-3" %>
  <% end %>
</div>

app/views/layouts/_notice.html.erb
<% if !flash[:notice].blank? %>
  <% full_flash = flash[:notice].split("|") %>
  <% if full_flash[0] == "danger" %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= full_flash[1] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% elsif full_flash[0] == "success" %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= full_flash[1] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% else %>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <%= full_flash[1] %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/layouts/_user_info.html.erb
<div class="col-6">
  <strong class="mr-3">
    <%= link_to "ToDoMVC", root_path %>
  </strong>
  <% if logged_in? %>
    welcome, <%= current_user.email %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeJune2019RailsTodomvc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/notice" %>

    <div class="container">
      <div class="row mt-3">
        <%= render "layouts/user_info" %>
        <%= render "layouts/access" %>
      </div>
    </div>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="row mt-4">
  <div class="col">
    <h3>ToDo MVC - App</h3>
  </div>
</div>
<div class="row">
  <div class="col">
    <hr>
  </div>
</div>
<div class="row">
  <!-- list begin -->
  <div class="col border my-1 mx-4 p-4 bg-dark text-white rounded shadow">
    <h4 class="mt-n2">All Lists</h4>
    <ul class="list-group text-dark">
      <li class="list-group-item py-3">
        <%= form_for @list do |f| %>
          <div class="form-row">
            <div class="col">
              <%= f.text_field :name, class: "form-control", placeholder: "#{@list.errors.full_messages_for(:name).first || 'Add a New List Name'}" %>
            </div>
          </div>
        <% end %>
      </li>
      <% @lists.each do |list| %>
        <li class="list-group-item py-3">
          <%= link_to make_title_case(list.name), list_path(list) %>
          <span class="float-right">
            <%= button_to list_path(list), method: :delete, class: "close" do %>
              <span aria-hidden="true">&times;</span>
            <% end %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
  <!-- list end -->
</div>

app/views/lists/show.html.erb
<div class="row mt-4">
  <div class="col">
    <h3>
      <%= make_title_case(@list.name) %>
    </h3>
  </div>
</div>
<div class="row">
  <div class="col">
    <hr>
  </div>
</div>
<div class="row">
  <div class="col">
    <%= link_to "<< Return to Lists", lists_path %>
  </div>
</div>
<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<div class="row">
  <!-- list begin -->
  <div class="col border my-1 mx-4 p-4 bg-dark text-white rounded shadow">
    <ul class="list-group text-dark">
      <li class="list-group-item py-3">
        <%= form_for [@list, @item] do |f| %>
          <div class="form-row">
            <div class="col">
              <%= f.text_field :description, class: "form-control", placeholder: "#{@item.errors.full_messages_for(:description).first || 'Add a New Item'}" %>
            </div>
          </div>
        <% end %>
      </li>
      <%= render collection: @list.items, partial: "items/item_list_item", as: :item %>
    </ul>
  </div>
  <!-- list end -->
</div>

app/views/site/index.html.erb
<div class="row mt-4">
  <div class="col">
    <h1>ToDo MVC - App</h1>
    <p><%= @welcome %></p>
  </div>
</div>
<div class="row">
  <div class="col">
  </div>
</div>
<div class="row">
  <!-- list begin -->
  <div class="col border my-1 mx-4 p-4 bg-dark text-white rounded shadow">
    <h4 class="mt-n2">List Title</h4>
    <ul class="list-group text-dark">
      <li class="list-group-item py-3">
        <form>
          <div class="form-row">
            <div class="col">
              <input type="text" class="form-control" placeholder="New Item">
            </div>
          </div>
        </form>
      </li>
      <li class="list-group-item py-3">
        <a href="#">List One</a>
      </li>
      <li class="list-group-item py-3">
        <a href="#">List Two</a>
      </li>
      <li class="list-group-item py-3">
        <a href="#">List Three</a>
      </li>
      <%# <li class="list-group-item py-3 bg-light text-dark">
        <div class="float-left pt-2">
          1 Item Left
        </div>
        <div class="text-center">
          <button type="button" class="btn btn-outline-primary">All</button>
          <button type="button" class="btn btn-outline-primary">Active</button>
          <button type="button" class="btn btn-outline-primary">Completed</button>
        </div>
      </li> %>
    </ul>
  </div>
  <!-- list end -->
</div>

app/views/users/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control", placeholder: "Please enter an email" %>
  <% if @user.errors[:email].present? %>
    <small id="emailHelp" class="form-text text-danger"><%= raw @user.errors.full_messages_for(:email).join("<br>") %></small>
  <% end %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control", placeholder: "Please enter a password" %>
  <% if @user.errors[:password].present? %>
    <small id="passwordHelp" class="form-text text-danger"><%= raw @user.errors.full_messages_for(:password).join("<br>") %></small>
  <% end %>
</div>

<div class="form-group">
  <%= f.submit submit_text, class: "btn btn-primary" %>
</div>

app/views/users/new.html.erb
<div class="row mt-5">
  <div class="col">
    <h3>User Registration</h3>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>

<div class="row mt-3">
  <div class="col">
    <%= form_for @user do |f| %>
      <%= render partial: "form", locals: { f: f, submit_text: "Register New User" } %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col">
    <hr>
  </div>
</div>